Added more logs
Added more logs

Simplified states

Update Dockerfiles (#10)

* Update Dockerfile source

Change the source of the Docker to use openshift upstream base images

  - openshift/origin-release:golang-1.13
  - openshift/origin-base

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

* Update Go version on Dockerfile.rhel7

Update Go version from 1.11 to 1.13

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

* Add GO111MODULE env var to Makefile

Add GO111MODULE env var to Makefile. THis has been a known issue when
running on ci platforms using Go 1.12 or below.

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

* mv Dockerfile.rhel7 Dockerfile.ci

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

Added new structure to SRO

Added new specialresource RDMA

Removed typos

Removed typos

diff --git a/recipes/gpu/4000-state-device-plugin.yaml b/recipes/gpu/4000-state-device-plugin.yaml
--- a/recipes/gpu/4000-state-device-plugin.yaml
+++ b/recipes/gpu/4000-state-device-plugin.yaml
@@ -1,13 +1,34 @@
 apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: specialresource-driver-validation-entrypoint
+  namespace: openshift-sro
+data:
+  entrypoint.sh: |-
+    #!/bin/bash
+    NUM_GPUS=$(nvidia-smi -L | wc -l)
+    if [ $NUM_GPUS -eq 0 ]; then
+      echo "ERROR No GPUs found"
+      exit 1
+    fi
+
+    cd /usr/local/cuda-10.2/cuda-samples/Samples/vectorAdd_nvrtc
+    ./vectorAdd_nvrtc
+
+    if [ ! $? -eq 0 ]; then
+      exit 1
+    fi
+---
+apiVersion: v1
 kind: ServiceAccount
 metadata:
-  name: nvidia-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
-  name: nvidia-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
 rules:
 - apiGroups:
@@ -22,34 +43,35 @@ rules:
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
-  name: nvidia-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
-  name: nvidia-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
 subjects:
 - kind: ServiceAccount
-  name: nvidia-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
 userNames:
-- system:serviceaccount:openshift-sro-operator:nvidia-device-plugin
+- system:serviceaccount:openshift-sro-operator:specialresource-device-plugin
 ---
 apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   labels:
-    app: nvidia-device-plugin-daemonset
-  name: nvidia-device-plugin-daemonset
+    app: specialresource-device-plugin
+  name: specialresource-device-plugin
   namespace: openshift-sro
   annotations:
     openshift.io/scc: hostmount-anyuid
-    callback: nvidia-device-plugin-daemonset
+    specialresource.openshift.io/state: "device-plugin"
+    specialresource.openshift.io/wait: "true"
 spec:
   selector:
     matchLabels:
-      app: nvidia-device-plugin-daemonset
+      app: specialresource-device-plugin
   template:
     metadata:
       # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
@@ -58,14 +80,14 @@ spec:
       annotations:
         scheduler.alpha.kubernetes.io/critical-pod: ""
       labels:
-        app: nvidia-device-plugin-daemonset
+        app: specialresource-device-plugin
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
-              - key: specialresource.openshift.io/driver-validation
+              - key: specialresource.openshift.io/runtime-enablement
                 operator: In 
                 values:
                 - ready 
@@ -78,10 +100,24 @@ spec:
       - key: nvidia.com/gpu
         operator: Exists
         effect: NoSchedule
-      serviceAccount: nvidia-device-plugin
+      serviceAccount: specialresource-device-plugin
+      initContainers:
+      - image: nvidia/samples:cuda10.2-vectorAdd
+        imagePullPolicy: Always
+        name: cuda-vector-add
+        command: ["/bin/entrypoint.sh"]
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop: ["ALL"]
+        volumeMounts:
+        - name: init-entrypoint
+          mountPath: /bin/entrypoint.sh
+          readOnly: true
+          subPath: entrypoint.sh
       containers:
       - image: nvidia/k8s-device-plugin:1.11 
-        name: nvidia-device-plugin-ctr
+        name: specialresource-device-plugin-ctr
         securityContext:
           privileged: true
         env:
@@ -94,6 +130,11 @@ spec:
         - name: device-plugin
           hostPath:
             path: /var/lib/kubelet/device-plugins
+        - name: init-entrypoint
+          configMap:
+            defaultMode: 0700
+            name: specialresource-driver-validation-entrypoint
+
       nodeSelector:
         node-role.kubernetes.io/worker: ""
         feature.node.kubernetes.io/pci-10de.present: "true"
diff --git a/recipes/gpu/6000-state-device-monitoring.yaml b/recipes/gpu/6000-state-device-monitoring.yaml
--- a/recipes/gpu/6000-state-device-monitoring.yaml
+++ b/recipes/gpu/6000-state-device-monitoring.yaml
@@ -1,13 +1,33 @@
 apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: specialresource-device-plugin-validation-entrypoint
+  namespace: openshift-sro
+data:
+  entrypoint.sh: |-
+    #!/bin/bash
+    NUM_GPUS=$(nvidia-smi -L | wc -l)
+    if [ $NUM_GPUS -eq 0 ]; then
+      echo "ERROR No GPUs found"
+      exit 1
+    fi
+
+    /usr/local/cuda-8.0/samples/0_Simple/vectorAdd/vectorAdd
+
+    if [ ! $? -eq 0 ]; then 
+      exit 1
+    fi
+---
+apiVersion: v1
 kind: ServiceAccount
 metadata:
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
   namespace: openshift-sro
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
   namespace: openshift-sro
 rules:
 - apiGroups:
@@ -22,17 +42,17 @@ rules:
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
   namespace: openshift-sro
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
 subjects:
 - kind: ServiceAccount
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
 userNames:
-- system:serviceaccount:openshift-sro:nvidia-dcgm-exporter
+- system:serviceaccount:openshift-sro:specialresource-metrics-exporter
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
@@ -69,12 +89,12 @@ apiVersion: v1
 kind: Service
 metadata:
   namespace: openshift-sro
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
   labels:
-    app: nvidia-dcgm-exporter
+    app: specialresource-metrics-exporter
 spec:
   selector:
-    app: nvidia-dcgm-exporter
+    app: specialresource-metrics-exporter
   type: ClusterIP
   ports:
   - name: dcgm
@@ -86,7 +106,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   namespace: openshift-sro
-  name: nvidia-dcgm-exporter
+  name: specialresource-metrics-exporter
 spec:
   endpoints:
   - port: dcgm 
@@ -96,7 +116,7 @@ spec:
     - openshift-sro
   selector:
     matchLabels:
-      app: nvidia-dcgm-exporter
+      app: specialresource-metrics-exporter
 ---
 # Node exporter collecting only GPU metrics from dcgm-exporter.
 # Except textfile collector, all other collectors that are enabled by default are disabled.
@@ -105,25 +125,28 @@ apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   labels: 
-    app: nvidia-dcgm-exporter
-  name: nvidia-dcgm-exporter
+    app: specialresource-metrics-exporter
+  name: specialresource-metrics-exporter
   namespace: openshift-sro
+  annotations: 
+    specialresource.openshift.io/state: "device-monitoring"
+    specialresource.openshift.io/wait: "true"
 spec:
   selector:
     matchLabels:
-      app: nvidia-dcgm-exporter
+      app: specialresource-metrics-exporter
   template:
     metadata:
       labels:
-        app: nvidia-dcgm-exporter
-      name: nvidia-dcgm-exporter
+        app: specialresource-metrics-exporter
+      name: specialresource-metrics-exporter
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
-              - key: specialresource.openshift.io/device-validation
+              - key: specialresource.openshift.io/device-plugin
                 operator: In 
                 values:
                 - ready 
@@ -132,8 +155,25 @@ spec:
       - key: nvidia.com/gpu
         operator: Exists
         effect: NoSchedule
-      serviceAccount: nvidia-dcgm-exporter
-      serviceAccountName: nvidia-dcgm-exporter
+      serviceAccount: specialresource-metrics-exporter
+      serviceAccountName: specialresource-metrics-exporter
+      initContainers:
+      - image: quay.io/openshift-psap/cuda-vector-add:v0.1
+        imagePullPolicy: Always
+        name: cuda-vector-add
+        command: ["/bin/entrypoint.sh"]
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop: ["ALL"]
+        resources:
+          limits:
+            nvidia.com/gpu:  # requesting all GPUs
+        volumeMounts:
+        - name: init-entrypoint
+          mountPath: /bin/entrypoint.sh
+          readOnly: true
+          subPath: entrypoint.sh
       containers:
       - image: quay.io/prometheus/node-exporter:v0.16.0
         name: node-exporter
@@ -193,7 +233,7 @@ spec:
           readOnly: true
           mountPath: /run/prometheus
       - image: nvidia/dcgm-exporter:1.4.6
-        name: nvidia-dcgm-exporter
+        name: specialresource-metrics-exporter
         securityContext:
           runAsNonRoot: false
           runAsUser: 0
@@ -214,6 +254,11 @@ spec:
       - name: collector-textfiles
         emptyDir:
           medium: Memory
+      - name: init-entrypoint
+        configMap:
+          defaultMode: 0700
+          name: specialresource-device-plugin-validation-entrypoint
+
       nodeSelector:
         node-role.kubernetes.io/worker: ""
         feature.node.kubernetes.io/pci-10de.present: "true"
